### PR TITLE
added sharedictionary tracking of processes requested to be killed in th...

### PR DESCRIPTION
**Pull request by CRuppert**
reference #257
DynamicEndpointRunner this allows the processes to be exited when
RecycleRoleOnError is set to true. This avoids the whole host from being
restarted when and endpoint is removed

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Thank you @CRuppert 
We have actually moved host to a repo on its own which is here https://github.com/Particular/NServiceBus.Host.AzureCloudService

I'll update [readme.md](https://github.com/Particular/NServiceBus.Azure/blob/develop/README.md) to let contributors know what went where.

**Comment by SeanFeldman** [comment]
Chad, could you please sign Contributor License Agreement here http://www.particular.net/contributors-license-agreement-consent?

**Comment by CRuppert** [comment]
All set. Thanks for taking the patch!

**Comment by SeanFeldman** [comment]
I'll need to move it to the new repo, if you want you can submit PR against that one as well. Original issue you've opened was moved there (https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/9)

Thank you again :)

**Comment by CRuppert** [comment]
@SeanFeldman I believe you should have this as PR 10 on the new repo now

**Pull request merged**
