### PR TITLE
GitHubSync update

### PR DESCRIPTION
**Pull request by particularbot**
This is an automated synchronization PR.

The following source template repositories were used:
* particular/RepoStandards

### CODE REVIEW

**Comment by ramonsmits** [comment]
The last release is marked as obsolete, see https://github.com/Particular/NServiceBus.Azure/releases/tag/7.0.0

I think this repo can be archived.

**Comment by SeanFeldman** [comment]
NServiceBus.Azure 6.2.7 [has Extended support](https://docs.particular.net/nservicebus/upgrades/supported-versions#persistence-packages-nservicebus-azure) until 2020-10-11. Do not archive.

**Comment by ramonsmits** [comment]
> NServiceBus.Azure 6.2.7 [has Extended support](https://docs.particular.net/nservicebus/upgrades/supported-versions#persistence-packages-nservicebus-azure) until 2020-10-11. Do not archive.

Thanks for mentioning extended support @seanfarmar as I thought extended support was already  expired for core 5

**Comment by andreasohlund** [comment]
Good catch, unarchived

**Pull request closed without merging**
